// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JPSoftworks.EditorBar
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidEditorBarPackageString = "ef5d9a25-5e0d-4428-8762-56d4dc816eeb";
        public static Guid guidEditorBarPackage = new Guid(guidEditorBarPackageString);

        public const string guidEditorBarPackageCmdSetString = "264c2d6c-e85c-4cbb-a800-0c412f8d91f1";
        public static Guid guidEditorBarPackageCmdSet = new Guid(guidEditorBarPackageCmdSetString);

        public const string guidImagesString = "8ec912c7-6f7f-457d-bbe8-318409383d92";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int EditorBarViewMenuGroup = 0x1120;
        public const int EditorBarViewSubMenu = 0x1130;
        public const int EditorBarViewSubMenuGroup = 0x1231;
        public const int EditorBarTextEditorToolbarGroup = 0x1140;
        public const int ToggleEditorBarCommand = 0x0100;
        public const int EditorBarOptionsCommand = 0x0101;
        public const int EditorBarFileActionMenu = 0x2000;
        public const int EditorBarFileActionMenuCopyPathGroup = 0x2001;
        public const int EditorBarFileActionMenuOpenFileGroup = 0x2002;
        public const int EditorBarFileActionMenuOpenFolderGroup = 0x2003;
        public const int EditorBarFileAction_OpenContainingFolderCommand = 0x2010;
        public const int EditorBarFileAction_OpenFileInDefaultEditorCommand = 0x2011;
        public const int EditorBarFileAction_OpenFileInExternalEditorCommand = 0x2012;
        public const int EditorBarFileAction_CopyFullPathCommand = 0x2013;
        public const int EditorBarFileAction_CopyRelativePathCommand = 0x2014;
        public const int bmpToggleEditorBar = 0x0001;
    }
}