// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JPSoftworks.EditorBar
{
    internal sealed partial class Vsix
    {
        public const string Id = "EditorBar.d5a61a21-bc87-477e-b916-ead20fb3fafb";
        public const string Name = "Editor Bar";
        public const string Description = @"Adds intuitive breadcrumbs to help you navigate file paths and code structure with ease.";
        public const string Language = "en-US";
        public const string Version = "3.0.1024";
        public const string Author = "Jiří Polášek";
        public const string Tags = "editor bar,path,file,breadcrumbs,location,project,directory,folder,structure,";
        public const bool IsPreview = false;
    }
}
