//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPSoftworks.EditorBar.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JPSoftworks.EditorBar.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Fragment.
        /// </summary>
        internal static string CodeFragment {
            get {
                return ResourceManager.GetString("CodeFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path: .
        /// </summary>
        internal static string FullPathLabel {
            get {
                return ResourceManager.GetString("FullPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This PC.
        /// </summary>
        internal static string LocalDriveRootName {
            get {
                return ResourceManager.GetString("LocalDriveRootName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous Files.
        /// </summary>
        internal static string MiscellaneousFilesName {
            get {
                return ResourceManager.GetString("MiscellaneousFilesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string NetworkRootName {
            get {
                return ResourceManager.GetString("NetworkRootName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \.
        /// </summary>
        internal static string SolutionRootName {
            get {
                return ResourceManager.GetString("SolutionRootName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp.
        /// </summary>
        internal static string TempRootName {
            get {
                return ResourceManager.GetString("TempRootName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top-level statements.
        /// </summary>
        internal static string TopLevelStatements {
            get {
                return ResourceManager.GetString("TopLevelStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Untitled document).
        /// </summary>
        internal static string UntitledDocument {
            get {
                return ResourceManager.GetString("UntitledDocument", resourceCulture);
            }
        }
    }
}
